### ISSUE TITLE
HTML string support

### ISSUE THREAD

**Issue by ivansabik** [fallanic/cheers#13]
Is it possible to support scraping from html? without making any HTTP request in case you somehow obtained the html. I was thinking maybe:

```javascript
config.html = '<body><div>Im an HTML</div></body>'
```

And assign priority or throw error in case both ```config.url``` and ```config.html``` found

**Comment by fallanic** [comment]
Hi,

you should use cheerio for that, it does what you need : https://github.com/cheeriojs/cheerio

**Comment by ivansabik** [comment]
In Cheerio you cant define a schema for what the definition of what you want to extract in each block
